### PR TITLE
Fixes for Issues 8 & 9.

### PR DESCRIPTION
**Pull request by ProfessorTom**
Student ticket form submission button is now replaced with a spinner that is the same color as the theme when waiting for the network. The spinner is replaced when the request readyState == DONE.

### CODE REVIEW

**Comment by freestylecoder** [comment]
Btw, I'm not ignoring this.  I'm in the middle of a HUGE branch, and I wanted to see how this looks on the page before I merge it.

**Comment by ProfessorTom** [comment]
I totally understand.

It's one thing to hack a couple of lines of Javascript together. It's quite another to make aesthetic code and site. Besides, I know you've been otherwise engaged this week.

**Comment by freestylecoder** [comment]
Call for Speakers just got to the staging site.  I'll hopefully get it to prod and merged tonight.  Then, I can look at this.

**Comment by freestylecoder** [comment]
Thank you, sir.

**Pull request merged**
