### PR TITLE
Update call for speakers date 2018

### PR DESCRIPTION
**Pull request by ProfessorTom**
all speaker related dates for 2018 just got bumped a week...manually

### CODE REVIEW

**Comment by freestylecoder** [comment]
That gets the important, public parts. There are the emails in the sessions controller, but I'll get those later.

Thank you. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by freestylecoder** [comment]
Fixes public dates

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ProfessorTom** [comment]
Smurf! I thought I was clever and got all of the places these dates need to change.

Should I file an issue for parameterizing these dates so they are in one place and easy to change for years to come?

**Comment by freestylecoder** [comment]
>Smurf! I thought I was clever and got all of the places these dates need to change. ...

@ProfessorTom I'm working on that. Did you notice that shiny new Events table that showed up. That's step one for that.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
